[package]
name = "fireside-query-engine"
description = "Firestore-compatible query evaluation for fireside"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
fireside-core-store = { path = "../core-store" }

[lints]
workspace = true
