[package]
name = "fireside-rest-front"
description = "Firestore REST and emulator-control frontend for fireside"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
axum.workspace = true
base64.workspace = true
fireside-core-store = { path = "../core-store" }
serde.workspace = true
serde_json.workspace = true
time.workspace = true

[lints]
workspace = true
