[package]
name = "fireside-rest-front"
description = "Firestore REST and emulator-control frontend for fireside"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[lints]
workspace = true
